version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: nest_postgres
    restart: always
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: nestdb
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nestuser"]
      interval: 5s
      timeout: 5s
      retries: 5
